services:
  postgres:
    image: postgres:16
    container_name: kamak_postgres
    restart: always
    environment:
      POSTGRES_USER: kamak
      POSTGRES_PASSWORD: sk3ysowk_45
      POSTGRES_DB: kamak_catalog
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: kamak_backend
    restart: always
    depends_on:
      - postgres
    working_dir: /app
    ports:
      - "3001:3000"
    env_file:
      - ./backend/.env.docker

  nginx:
    image: nginx:alpine
    container_name: kamak_nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data: